[package]
name = "bolter"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
elfkit = {path = "elfkit"}
colored = "1"
goblin = "0.0.11"
byteorder = "1"
sha2 = "0.6"

#digest = { version = "0.6", features = ["std"]}

